name: Agile_Modbus

on:
  push:
    branches:
      # Make sure this is the branch name you are using
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  example-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # If your document requires Git submodules, uncomment the next line
          # submodules: true

      - name: Install Tools
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install cmake

      - name: Example Compile
        shell: bash
        run: |
          cd examples
          cmake -B build
          cmake --build build

  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # If your document requires Git submodules, uncomment the next line
          # submodules: true

      - name: Install Tools
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get -qq install doxygen graphviz

      - name: generat doxygen html
        shell: bash
        run: |
          ls
          cd doc/doxygen
          doxygen Doxyfile

      - name: Deployment documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # This is the branch name to which the document is deployed
          branch: gh-pages
          folder: doc/doxygen/output
